services:
  chatserv-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - CHATSERV_Logging__LogLevel__Default=Information
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pAs5w0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - CHATSERV_House__AvailableMessages__0=Hello!
      - CHATSERV_House__AvailableMessages__1=How are you?
      - CHATSERV_House__AvailableMessages__2=I'm good!
      - CHATSERV_House__AvailableMessages__3=Not great...
      - CHATSERV_Settings__ChatBaseUrl=wss://localhost:5002/
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/:ro
    ports:
      - "5002:5002"
    networks:
      chatserv_net:

  chatserv-web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "5003:443"
    networks:
      chatserv_net:
networks:
  chatserv_net: