services:
  chatserv-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pAs5w0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - CHATSERV_API_House__AvailableMessages__0=Hello!
      - CHATSERV_API_House__AvailableMessages__1=How are you?
      - CHATSERV_API_House__AvailableMessages__2=I'm good!
      - CHATSERV_API_House__AvailableMessages__3=Not great...
      - CHATSERV_API_Settings__ChatBaseUrl=ws://localhost:5020/
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/:ro
    ports:
      - "5020:5020"
    networks:
      chatserv_net:

networks:
  chatserv_net: